### ISSUE TITLE
MasterNode: "could not allocate vin for collateralAddress" error

### ISSUE THREAD

**Issue by LinuxETC** [sagacrypto/SagaCoin#4]
**Release Version:** 
sagacoin_1.0.0.4_ubuntu16.04.tar.gz

**Error Message:**
From the ~/.SagaCoin/debug.log file:
```
CActiveMasternode::GetMasterNodeVinForPubKey - Could not locate specified vin from possible list
Register::Register() - Error: could not allocate vin for collateralAddress
```

**Details:**
The MasterNode was up and running for ~12 hours (this time; had a similar incident before) and just "stopped".  The wallet is showing as "unlocked" (e.g., the padlock icon is in an "unlocked" position).  The 2500SAGA deposit was in place properly with a few payment/rewards received after this as well.

Questions and/or feedback are welcomed.  Thanks in advance.

**Comment by LinuxETC** [comment]
Additional notes:
After stopping the sagacoind service/daemon, tried removing the ~/.SagaCoin/.lock files on the VPS and wallet side.  Restarted sagacoind on the VPS, then wallet.  Was unable to start up the MasterNode via the wallet.

Current work around solution: 
(1) Create a new MN label within the wallet.
(2) Do a self transfer of 2500 SAGA to the new MN label.
(3) Start MN via new label.

Current failure rate is ~1 week time frame from the past three encounters of this.

**Comment by cedriking** [comment]
Hello @LinuxETC , I had the same issue, my problem was because the masternode wallet was staking, so if you go and see the inputs, you will have your 2500 split into 1250.some decimals.

To solve the issue, make sure you have ```staking=0``` on your sagacoin.conf

My workaround for when it happened was different:
- Withdraw your total balance from the masternode.
- Restart the masternode wallet.
- Restart the local wallet (if running one).
- Send the amount back to the masternode and wait for it to be confirmed.
- Start the masternode, and it works.

As long as you have staking=0 and your local wallet that has the masternode locked (not staking), then it doesn't happen.

**Comment by Squazz** [comment]
@GoldZeus I just experienced this too. My wallet is locked and I have `staking=0` in my config

**Comment by Squazz** [comment]
I just found out that it helped to unlock the wallet, then I was able to start the MN

**Comment by sagacrypto** [comment]
So issue solved and I close the case.

**Comment by mkoshevoi** [comment]
Hi! I have the same problem. Can u help me?
What does it mean?  (2) Do a self transfer of 2500 SAGA to the new MN label. (LinuxETC)
